apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notification-service
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    MATRIX_API_TOKEN: AgAVUVkUe3oPI6/a7vLAmkfsy8VjnLZhMAQuUvDu0z9nQEphCxh4LOAiIy7DkD1b0qGhknXe+y+j/mqEnZQtNVsc7KtQC2261/INLt931lJ1M+mY32q7Gx9r68k+dMMaN8pgMlO7yaefN4Be1nuiTNJrCJSieKyEm1G9kwxe23N8b0UsyZjau/XgIeF7S0q2nbvtXlOXIdO0OOd3EAUPaGBrWklHnc1G/J/bHqdo5F/M0CqLkcTmSmIRez1vSXtUjv/AMCqwCT0dhxseRb30o7bNDzdoZtxXtfx5GH00JVIJT1SBhvWwQWz66N8lNlFB7+W8V17AYemOqzRymfjm075uiPCAhksSGYzA/K8ef243TsY8rGiD1BjYHYeaCpspaKPnqeqWecrW9Q4dya/kz4YpX5DeutlLqDa4smVEfljOgbQ2qDqMQftyYUq01Y0dk6M7zgc3xFtPRCOZISxhHYxLkEf9LU7vR5ZnfCki7rzohlrrjbvwU3eeoIvU/E2BiFwHWzgovb6dSaEX/OhLMB4SkFEd2jIBm51x24gJ2RKbHUSl4BRQHYOGEv/7Uaxn4ks0pe966D4mUhp49WFvHx+5zpL8CBDDRGBgIJbDYWwvcF1iRvorjF3pxybofNYp/xBUiOP2O/wIkwqVsxTI7NmM2fRaoCzjHM4TwLNu+2JvYJwqFuVgLvcTp9YEAKLVXk+T8AHUefJfDJR1CQyQ9c0hggp6/3wzMSImA1HfPOdjWHyTaPtOtj5xQluxb1FNvR++ghbM
  template:
    metadata:
      creationTimestamp: null
      name: notification-service
      namespace: monitoring