apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notification-service
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    MATRIX_API_TOKEN: AgCxDwh/YWS9ZtrPEmHS5Ow+/loRuIytkuVcIwBNI8IGV7IqoIunev64kYfin1to6czygAFTxjAfXBpIK/d7M3ddtwjeVwfF8bJEFZ2tWE3bPddjeuyORq1sy+erLekYE9CVWJPLz1xES+Ktdnvlk2RQ4oGlVzlw79QF9GCumnTxEl8Wpn9HwBOKvmeRkhk420ht3ulw5ZyLJ+3siF3a0qQoDyVl8yak4gGzGeQ0IN11zV5Bo/+mgDtfqdgAUyFAainWr6SrEsV35qvCyfBEAZylZFg0Xd/74aFdahrBl1UesGv3cr32KjsTKGfsNbY/zPc+xqYgU0jzdkXR+elMJlv39gNc5/717oYgZqjQh5Fr/vXDyYBHhtW6eKqWSxSkNm31ZCwt6KgXU7ZNKHKtSaRsm0YlEZGGgFNrIvHgavsZT7wUgrYdqd5EMiosAIx7I+XCucinBxQa6Xya8X7Z/DdGn5FWUI5leXU0kblWgY1igO4h1ypwiawycpNyRczXRpmdBuXwvBu4UjWb2+VlSv7jClwW/TnnedmQKSn3O9QY6sxpEhmH450xTOqdBK2P8SjRwwbBFrslhIygsxCKH+9g40/OFUrKQ7t3gROA0ieFpZlW1wDut2praeWA2Hls7ZlB75MmPWXEx/BPuhTkEPtflxxb+jhAjusE3Tqx5NN2sT0yNe332SBtplH2TTltn7sV73tNX8BPhP6+0+z0HJNKig64wkIYMcZwFztTTvXWf0PxQGyF2i+CYqiYMbT2Eg/K3J2/
  template:
    metadata:
      creationTimestamp: null
      name: notification-service
      namespace: monitoring