---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-cluster
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
      argocd.argoproj.io/instance: rabbitmq
      app.kubernetes.io/name: rabbitmq-ha-cluster
  endpoints:
  - port: prometheus
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - rabbitmq
