apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forward-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: "2.2.2"
    chart: traefik-forward-auth
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            serviceAccount:
              create: false
              name: traefik
              annotations:
                iam.gke.io/gcp-service-account: ARGOCD_ENV_CLUSTER_NAME-traefik@ARGOCD_ENV_GOOGLE_PROJECT.iam.gserviceaccount.com
            env:
              TZ: UTC
              URL_PATH: /_oauth
              DEFAULT_PROVIDER: google
              LOG_LEVEL: debug
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
