---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-credentials-admin
  namespace: rabbitmq
spec:
  encryptedData:
    host: {{ .Values.sealedSecrets.admin.host }}
    port: {{ .Values.sealedSecrets.admin.port }}
    provider: {{ .Values.sealedSecrets.admin.provider }}
    type: {{ .Values.sealedSecrets.admin.type }}
    username: {{ .Values.sealedSecrets.admin.username }}
    password: {{ .Values.sealedSecrets.admin.password }}
    default_user.conf: {{ .Values.sealedSecrets.admin.conf }}
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-credentials-admin
      namespace: rabbitmq
