apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: rabbitmq
  endpoints:
    - port: "http"
      interval: 30s
      path: /